// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	Street string `json:"street"`
	City   string `json:"city"`
	State  string `json:"state"`
	Zip    string `json:"zip"`
}

type CreateAddress struct {
	Street *string `json:"street,omitempty"`
	City   *string `json:"city,omitempty"`
	State  *string `json:"state,omitempty"`
	Zip    *string `json:"zip,omitempty"`
}

type CreateJobListingInput struct {
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Company     string         `json:"company"`
	URL         string         `json:"url"`
	Address     *CreateAddress `json:"address"`
}

type DeleteJobResponse struct {
	DeletedJobID string `json:"deletedJobId"`
}

type JobListing struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Company     string   `json:"company"`
	URL         string   `json:"url"`
	Address     *Address `json:"address"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateJobListingInput struct {
	Title       *string        `json:"title,omitempty"`
	Description *string        `json:"description,omitempty"`
	Company     *string        `json:"company,omitempty"`
	URL         *string        `json:"url,omitempty"`
	Address     *CreateAddress `json:"address"`
}
